base_url = "https://i1i1.github.io/whoami"
compile_sass = false
theme = "anemone"
build_search_index = false

[markdown]
highlight_code = true
smart_punctuation = true

[extra]
author = "i1i1"
header_nav = [
  { name_en = "/home/", url = "$BASE_URL" },
  { name_en = "/github/", url = "https://github.com/i1i1" },
  { name_en = "/email/", url = "mailto:vanyarybin1@live.ru" },
  { name_en = "/telegram/", url = "https://t.me/i1i1r" },
]