name: "Render Resume"

on:
  push:
    branches:
        - master

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v23
    - run: nix build -L .#cv
    - uses: actions/upload-artifact@v4
      with:
        name: cv.zip
        path: "result/*.pdf"
